# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20161104_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='erere', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='erere', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=b'/media/'),
        ),
    ]
