# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20161107_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=b'media'),
        ),
    ]
