# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20161107_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
    ]
